In [1]:
# Intro to deep learning course
# Basic Perceptron implementation in numpy
import numpy as np
import matplotlib.pyplot as plt # used to plot


# method for the forward propagation method
class Layer:
    def __init__ (self,activation,h_size, output_size,lr=0.05):
        
        self.activation = activation # activation function(string)
        self.h_size = h_size # size of the input vector 
        self.lr = lr # learning rate 
        self.h_l = None # input vector
        self.d_transfer = None # derivative of the transfer function
        self.output_size = output_size
        self.weights = np.random.rand(output_size, h_size)
        self.weights = 5.0*np.matrix(self.weights) # weight matrix
        self.bias_vec = np.matrix(np.random.rand(output_size))
        self.gradient = np.matrix(np.zeros(output_size))
        
    #sigmoid function   
    def sigmoid(self,x):
        return 1.0/(1+np.exp(-x))
    #derivative of the sigmoid function 
    def dsigmoid(self,x):
        return np.multiply(x,(1.0-x))
    
    
    #forward prop for the layer(accepts input from the previous layer)
    #vectors are assumed to be row vector, vector transpose 
    def layer_forward(self,h_l): #input vector forward propagation
        self.h_l = h_l
        output = self.weights*self.h_l+self.bias_vec # assume the x vector is treated as a matrix instead of a numpy array
        if (self.activation == "sigmoid"):
            output = self.sigmoid(output)
            self.d_transfer = self.dsigmoid(output) #  capture the derivative of the transfer function with respect to its input
        return output
    
    
    #back prop for the layer (accept gradient from the next layer)
    def layer_backprop(self,grad_l):
        
        back_grad_W = np.multiply(grad_l,self.d_transfer) # back grad is the derivative of the Loss function with respect to input h_l
        # updating parameters with regularization 
        self.gradients = self.gradient -self.lr*(back_grad_W*self.h_l.T) #+lambda_val*np.linalg.norm(self.weights,2)
        self.bias_vec = self.bias_vec -self.lr*grad_l
        grad_l = grad_l
        return back_grad_W.T
    
    #MSE  x and t are treated as matrices
    
def MSE(x,t):
        y = (x-t).T*(x-t)
        y = y/2.0*len(np.array(x).tolist())
        return y
        
    
def dMSEdx(y,t):
        return (y-t)
        
        
        

In [2]:
perceptron = Layer(activation = "sigmoid" , h_size =3,output_size=1)
print(perceptron.weights)

np.array(perceptron.layer_forward(np.matrix([1,2,3]).T)).tolist()[0]


[[2.34626447 4.89000587 0.24276698]]


[0.9999982395007044]

In [3]:
print(np.matrix([1,2,3]).T)
print(np.matrix([1,2,3]))
print("\n")
print((np.matrix([1,2,3])*np.matrix([1,2,3]).T))
MSE(np.matrix([1,2,3]).T,np.matrix([1.5,2,3.5]).T)

[[1]
 [2]
 [3]]
[[1 2 3]]


[[14]]


matrix([[0.75]])

In [22]:
target = []
x_input = []
def equation(x,y,z):
    return (2.0*x)+(3.0*y)+(1.0*z)+3.0
for i in range(100):
    x_input.append([i,i,i])
    target.append([equation(i,i,i)])
print(np.shape(x_input))
#print(np.shape(np.array(np.matrix(target)).tolist()))
#print(type(np.array(np.matrix(target)).tolist()))


#testing backpropagation
grad = dMSEdx(np.matrix([6.0]).T, np.matrix([6.055]).T)
grad
perceptron.layer_backprop(grad)
perceptron.weights

(100, 3)


matrix([[2.34626447, 4.89000587, 0.24276698]])

In [25]:
p = Layer(activation = 'sigmoid',h_size=3,output_size=1,lr=0.5) # p for perceptron
for epoch in range(300):
    for i in range(100):
        target_vec = np.matrix(target[i]).T
        x_vec = np.matrix(x_input[i]).T
        y_vec = p.layer_forward(x_vec)
        grad = dMSEdx(y_vec,target_vec)
        p.layer_backprop(grad)
print(p.weights) 

[[3.90406599 2.71322907 1.28069543]]


In [7]:
# Method to train a layer. We can later add more layers to form a neural network 
my_perceptron = Layer(activation='sigmoid',h_size=3,output_size=1)
print(np.matrix(target[0]).T)
print(np.matrix(x_input[0]).T)
for i in range(len(x_input)):
    target_vec = np.matrix(target[i]).T
    x_vec = np.matrix(x_input[i]).T
    y_vec = my_perceptron.layer_forward(x_vec)
    grad = dMSEdx(y_vec,target_vec)
    my_perceptron.layer_backprop(grad,0.5)


[[3.]]
[[0]
 [0]
 [0]]


TypeError: layer_backprop() takes 2 positional arguments but 3 were given